/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import connexion.Login;
import connexion.Logout;
import java.util.Date;
import javax.swing.JFrame;
import utilisateur.ListeDepartements;
import utilisateur.ListeEtudiants;
import utilisateur.ListeFilières;

/**
 *
 * @author danieljoaquimpaulino
 */
public class MenuProjet extends javax.swing.JFrame {

    /**
     * Creates new form MenuProjet
     */
    public MenuProjet() {
        initComponents();
        
          this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMENU = new javax.swing.JPanel();
        jButtonEtud = new javax.swing.JButton();
        jButtonDpa = new javax.swing.JButton();
        jButtonFil = new javax.swing.JButton();
        jButtonUtil = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButtonLisDep = new javax.swing.JButton();
        jButtonLFil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        nicknameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabnomUt = new javax.swing.JLabel();
        jButtoMEN = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelMENU.setBackground(java.awt.Color.white);
        jPanelMENU.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jButtonEtud.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEtud.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonEtud.setForeground(java.awt.Color.white);
        jButtonEtud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-student_male.png"))); // NOI18N
        jButtonEtud.setText(" ETUDIANT      ");
        jButtonEtud.setBorder(null);
        jButtonEtud.setContentAreaFilled(false);
        jButtonEtud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEtud.setDisabledIcon(null);
        jButtonEtud.setEnabled(false);
        jButtonEtud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEtud.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonEtud.setOpaque(true);
        jButtonEtud.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonEtud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEtudActionPerformed(evt);
            }
        });

        jButtonDpa.setBackground(new java.awt.Color(0, 102, 204));
        jButtonDpa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonDpa.setForeground(java.awt.Color.white);
        jButtonDpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-department_1.png"))); // NOI18N
        jButtonDpa.setText("DEPARTEMENT");
        jButtonDpa.setBorder(null);
        jButtonDpa.setContentAreaFilled(false);
        jButtonDpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDpa.setDisabledIcon(null);
        jButtonDpa.setEnabled(false);
        jButtonDpa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDpa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDpa.setOpaque(true);
        jButtonDpa.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonDpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDpaActionPerformed(evt);
            }
        });

        jButtonFil.setBackground(new java.awt.Color(0, 102, 204));
        jButtonFil.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonFil.setForeground(java.awt.Color.white);
        jButtonFil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-classroom_1.png"))); // NOI18N
        jButtonFil.setText("FILIERE         ");
        jButtonFil.setAutoscrolls(true);
        jButtonFil.setBorder(null);
        jButtonFil.setContentAreaFilled(false);
        jButtonFil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFil.setDisabledIcon(null);
        jButtonFil.setEnabled(false);
        jButtonFil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonFil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonFil.setOpaque(true);
        jButtonFil.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilActionPerformed(evt);
            }
        });

        jButtonUtil.setBackground(new java.awt.Color(0, 102, 204));
        jButtonUtil.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonUtil.setForeground(java.awt.Color.white);
        jButtonUtil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add_user_group_man_man_1.png"))); // NOI18N
        jButtonUtil.setText("UTILISATEURS");
        jButtonUtil.setBorder(null);
        jButtonUtil.setContentAreaFilled(false);
        jButtonUtil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUtil.setDisabledIcon(null);
        jButtonUtil.setEnabled(false);
        jButtonUtil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUtil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonUtil.setOpaque(true);
        jButtonUtil.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUtilActionPerformed(evt);
            }
        });

        jButtonList.setBackground(new java.awt.Color(0, 102, 204));
        jButtonList.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonList.setForeground(java.awt.Color.white);
        jButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8ETUcompose.png"))); // NOI18N
        jButtonList.setText("L. ETUDIANTS     ");
        jButtonList.setBorder(null);
        jButtonList.setContentAreaFilled(false);
        jButtonList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonList.setDisabledIcon(null);
        jButtonList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonList.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonList.setOpaque(true);
        jButtonList.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListActionPerformed(evt);
            }
        });

        jButtonLisDep.setBackground(new java.awt.Color(0, 102, 204));
        jButtonLisDep.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonLisDep.setForeground(java.awt.Color.white);
        jButtonLisDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit_property.png"))); // NOI18N
        jButtonLisDep.setText("L. DEPARTEM ");
        jButtonLisDep.setBorder(null);
        jButtonLisDep.setContentAreaFilled(false);
        jButtonLisDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLisDep.setDisabledIcon(null);
        jButtonLisDep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLisDep.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonLisDep.setOpaque(true);
        jButtonLisDep.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonLisDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLisDepActionPerformed(evt);
            }
        });

        jButtonLFil.setBackground(new java.awt.Color(0, 102, 204));
        jButtonLFil.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButtonLFil.setForeground(java.awt.Color.white);
        jButtonLFil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-edit_property_1.png"))); // NOI18N
        jButtonLFil.setText("L. FILIERE  ");
        jButtonLFil.setBorder(null);
        jButtonLFil.setContentAreaFilled(false);
        jButtonLFil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLFil.setDisabledIcon(null);
        jButtonLFil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLFil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonLFil.setOpaque(true);
        jButtonLFil.setPreferredSize(new java.awt.Dimension(200, 70));
        jButtonLFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLFilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMENULayout = new javax.swing.GroupLayout(jPanelMENU);
        jPanelMENU.setLayout(jPanelMENULayout);
        jPanelMENULayout.setHorizontalGroup(
            jPanelMENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMENULayout.createSequentialGroup()
                .addGroup(jPanelMENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMENULayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMENULayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMENULayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonEtud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMENULayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMENULayout.createSequentialGroup()
                                .addGroup(jPanelMENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanelMENULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLisDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMENULayout.setVerticalGroup(
            jPanelMENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMENULayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEtud, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButtonLisDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLFil, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel3.setBackground(java.awt.Color.white);

        nicknameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        nicknameLbl.setForeground(new java.awt.Color(153, 0, 51));
        nicknameLbl.setText("Users");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8SShutdown.png"))); // NOI18N
        jLabel1.setText("Deconnecter");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-checked_user_male.png"))); // NOI18N

        JLabnomUt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        JLabnomUt.setForeground(new java.awt.Color(0, 102, 204));
        JLabnomUt.setText("Nom");

        jButtoMEN.setBackground(java.awt.Color.white);
        jButtoMEN.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButtoMEN.setForeground(new java.awt.Color(0, 51, 102));
        jButtoMEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-top_menu_1.png"))); // NOI18N
        jButtoMEN.setText("MENU");
        jButtoMEN.setBorder(null);
        jButtoMEN.setContentAreaFilled(false);
        jButtoMEN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtoMEN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtoMEN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtoMEN.setOpaque(true);
        jButtoMEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoMENActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtoMEN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabnomUt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtoMEN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nicknameLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JLabnomUt)
                                .addGap(11, 11, 11)))
                        .addGap(46, 46, 46))))
        );

        jLabelDate.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(0, 51, 102));
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate.setText("Date");

        jPanel1.setBackground(java.awt.Color.white);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Copyright© 2020");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(375, 375, 375))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("GESTION DES ETUDIANTS");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8Graduation.png"))); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-books.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMENU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelMENU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEtudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEtudActionPerformed
        // TODO add your handling code here:

        Etudiant etud = new Etudiant();

        etud.setVisible(true);
        etud.pack();
        etud.setLocationRelativeTo(null);
        etud.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    
    }//GEN-LAST:event_jButtonEtudActionPerformed

    private void jButtonDpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDpaActionPerformed
        // TODO add your handling code here:

        Departement dp = new Departement();
        dp.setVisible(true);
              dp.pack();
        dp.setLocationRelativeTo(null);
        dp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);


    }//GEN-LAST:event_jButtonDpaActionPerformed

    private void jButtonFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilActionPerformed
        // TODO add your handling code here:

        Filiere f = new Filiere();
        f.setVisible(true);
        
        f.pack();
        f.setLocationRelativeTo(null);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);


    }//GEN-LAST:event_jButtonFilActionPerformed

    private void jButtonUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUtilActionPerformed
        // TODO add your handling code here:

        Utilisateur ut = new Utilisateur();

        ut.setVisible(true);
                ut.pack();
        ut.setLocationRelativeTo(null);
        ut.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);



    }//GEN-LAST:event_jButtonUtilActionPerformed

    private void jButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListActionPerformed

        ListeEtudiants ut= new ListeEtudiants();
        ut.setVisible(true);
         ut.pack();
        ut.setLocationRelativeTo(null);
        ut.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonListActionPerformed

    private void jButtonLisDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLisDepActionPerformed

        ListeDepartements dp= new ListeDepartements();
        dp.setVisible(true);
        dp.pack();
        dp.setLocationRelativeTo(null);
        dp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonLisDepActionPerformed

    private void jButtonLFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLFilActionPerformed

        ListeFilières lf= new ListeFilières();

        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButtonLFilActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        
         Login loginForm = new Login();
         Logout.logOut(this, loginForm);
        
     
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        Date dt = new Date();
        
        jLabelDate.setText(dt.toString() );
    }//GEN-LAST:event_formWindowActivated

    private void jButtoMENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoMENActionPerformed
        // TODO add your handling code here:

//         int pos = jButtoMEN.getX();
//         
//         if (pos >5){
//         
//              Animacion.Animacion.mover_izquierda(  210,5 , 2,2,jButtoMEN);
//              Animacion.Animacion.mover_izquierda(  200, 0, 2,2,jPanelMENU);
//
//         
//         }else{
//         
//             Animacion.Animacion.mover_izquierda(  5, 210, 2,2,jButtoMEN);
//              Animacion.Animacion.mover_izquierda(  -200, 5, 2,2,jPanelMENU);
//
//         
//         
//         }

    }//GEN-LAST:event_jButtoMENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProjet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JLabnomUt;
    private javax.swing.JButton jButtoMEN;
    public static javax.swing.JButton jButtonDpa;
    public static javax.swing.JButton jButtonEtud;
    public static javax.swing.JButton jButtonFil;
    private javax.swing.JButton jButtonLFil;
    private javax.swing.JButton jButtonLisDep;
    private javax.swing.JButton jButtonList;
    public static javax.swing.JButton jButtonUtil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelMENU;
    public static javax.swing.JLabel nicknameLbl;
    // End of variables declaration//GEN-END:variables
}
